
const moveDataDict = {
	'mov10': [
		{
			type: 'rotateTo',
			time: 0,
			duration: 0,
			angle: 90,
		},
		{
			type: 'moveTo',
			time: 500,
			duration: 500,
			x: 0,
			y: 160,
		},
		{
			type: 'shot',
			time: 1000,
			duration: 1000,
			interval: 200,
		},
		{
			type: 'shot',
			time: 3000,
			duration: 1000,
			interval: 200,
		},
		{
			type: 'moveTo',
			time: 5000,
			duration: 2000,
			x: 0,
			y: 480,
		},
	],
	'mov11': [
		{
			type: 'rotateTo',
			time: 0,
			duration: 0,
			angle: 45,
		},
		{
			type: 'moveTo',
			time: 0,
			duration: 0,
			x: -80,
			y: -80,
		},
		{
			type: 'moveTo',
			time: 0,
			duration: 200,
			x: 0,
			y: 0,
		},
		{
			type: 'rotateTo',
			time: 200,
			duration: 200,
			angle: 60,
		},
		{
			type: 'shot',
			time: 1000,
			duration: 1000,
			interval: 200,
		},
		{
			type: 'shot',
			time: 3000,
			duration: 1000,
			interval: 200,
		},
		{
			type: 'rotateTo',
			time: 4800,
			duration: 200,
			angle: 45,
		},
		{
			type: 'moveTo',
			time: 5000,
			duration: 2000,
			x: 480,
			y: 480,
		},
	],
	
	'mov20': [
		{
			type: 'rotateTo',
			time: 0,
			duration: 0,
			angle: 0,
		},
		{
			type: 'shot',
			time: 500,
			duration: 5000,
			interval: 150,
		},
		{
			type: 'moveTo',
			time: 0,
			duration: 4000,
			x: 0,
			y: 320,
		},
		{
			type: 'moveTo',
			time: 4000,
			duration: 1000,
			x: 0,
			y: 480,
		},
	],
};

const blockArrDict = {
	'blc10': [
		{
			'time': 500,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': 20, 'y': -240 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 1000,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': 40, 'y': -260 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 1500,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': 0, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
	],
	'blc20': [
		{
			'time': 500,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': -80, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 600,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': -40, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 700,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': 0, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 800,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': 40, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 900,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': 80, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
	],
	'blc30': [
		{
			'time': 500,
			'type': '',
			'moveDataName': 'mov20',
			'pos': { 'x': -100, 'y': -160 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 2500,
			'type': '',
			'moveDataName': 'mov20',
			'pos': { 'x': 100, 'y': -160 },
			'scale': { 'x': -1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 5000,
			'type': '',
			'moveDataName': 'mov20',
			'pos': { 'x': -100, 'y': -160 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 5000,
			'type': '',
			'moveDataName': 'mov20',
			'pos': { 'x': 100, 'y': -160 },
			'scale': { 'x': -1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
	],
	'blc40': [
		{
			'time': 500,
			'type': '',
			'moveDataName': 'mov20',
			'pos': { 'x': -100, 'y': -160 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 1000,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': 40, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 2500,
			'type': '',
			'moveDataName': 'mov20',
			'pos': { 'x': 100, 'y': -160 },
			'scale': { 'x': -1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 3500,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': -40, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 5000,
			'type': '',
			'moveDataName': 'mov20',
			'pos': { 'x': -100, 'y': -160 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 5000,
			'type': '',
			'moveDataName': 'mov20',
			'pos': { 'x': 100, 'y': -160 },
			'scale': { 'x': -1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 6000,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': -40, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 6000,
			'type': '',
			'moveDataName': 'mov10',
			'pos': { 'x': -40, 'y': -280 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
	],
	'blc50': [
		{
			'time': 500,
			'type': '',
			'moveDataName': 'mov11',
			'pos': { 'x': -80, 'y': -80 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 700,
			'type': '',
			'moveDataName': 'mov11',
			'pos': { 'x': -100, 'y': -40 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
		{
			'time': 900,
			'type': '',
			'moveDataName': 'mov11',
			'pos': { 'x': -60, 'y': -120 },
			'scale': { 'x': 1, 'y': 1 },
			'delay': 200,
			'enemyCount': 1,
		},
	],
};

const waveData = [
	{
		'scale': { 'x': 1, 'y': 1 },
		'blocks': blockArrDict['blc10'],
	},
	{
		'scale': { 'x': -1, 'y': 1 },
		'blocks': blockArrDict['blc50'],
	},
	{
		'scale': { 'x': -1, 'y': -1 },
		'blocks': blockArrDict['blc10'],
	},
	{
		'scale': { 'x': 1, 'y': -1 },
		'blocks': blockArrDict['blc50'],
	},
	{
		'scale': { 'x': 1, 'y': 1 },
		'blocks': blockArrDict['blc20'],
	},
	{
		'scale': { 'x': -1, 'y': -1 },
		'blocks': blockArrDict['blc20'],
	},
	{
		'scale': { 'x': 1, 'y': 1 },
		'blocks': blockArrDict['blc30'],
	},
	{
		'scale': { 'x': 1, 'y': 1 },
		'blocks': blockArrDict['blc40'],
	},	
];


